# Generated by Django 3.2.9 on 2021-11-06 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_question_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionForGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('deadline', models.DateField(default=datetime.date.today)),
                ('score', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.question')),
            ],
            options={
                'unique_together': {('question', 'grade')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='grades',
            field=models.ManyToManyField(through='school.QuestionForGrade', to='school.Grade'),
        ),
    ]
