# Generated by Django 3.2.9 on 2021-11-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_profile_id_grade_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjournal',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='studentjournal',
            name='correct',
            field=models.BooleanField(default=None),
        ),
    ]
