# Generated by Django 3.2.9 on 2021-12-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20211120_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='grades',
        ),
        migrations.AddField(
            model_name='questionforgrade',
            name='theme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='school.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='questionforgrade',
            unique_together={('theme', 'grade')},
        ),
        migrations.RemoveField(
            model_name='questionforgrade',
            name='question',
        ),
    ]
