# Generated by Django 3.2.9 on 2021-12-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_rename_theme_id_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionforgrade',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_for_grade', to='school.theme'),
        ),
    ]
