# Generated by Django 3.2.9 on 2022-02-14 13:25

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_questionforgrade_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
