# Generated by Django 3.2.9 on 2021-11-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
    ]
