# Generated by Django 3.2.9 on 2021-11-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_membership_inviter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('group', 'person')},
        ),
    ]
