# Generated by Django 3.2.9 on 2021-11-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='profile',
            new_name='profile_id',
        ),
    ]
