# Generated by Django 3.2.9 on 2021-11-20 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_questionforgrade_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=None)),
                ('date', models.DateField(default=datetime.date.today)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'verbose_name': 'Журнал студента',
                'verbose_name_plural': 'Журнал студентов',
                'unique_together': {('student', 'question')},
            },
        ),
    ]
